# Vocab building
save_data: ../data/new_mayr_data_09-19-23/preprocessed_augm_2x/run/chem_pred
src_vocab: ../data/new_mayr_data_09-19-23/preprocessed_augm_2x/run/chem_pred.vocab.src
tgt_vocab: ../data/new_mayr_data_09-19-23/preprocessed_augm_2x/run/chem_pred.vocab.tgt
overwrite: False

data:
    corpus_1:
        path_src: ../data/new_mayr_data_09-19-23/preprocessed_augm_2x/src-train.csv
        path_tgt: ../data/new_mayr_data_09-19-23/preprocessed_augm_2x/tgt-train.csv
    valid:
        path_src: ../data/new_mayr_data_09-19-23/preprocessed_augm_2x/src-val.csv
        path_tgt: ../data/new_mayr_data_09-19-23/preprocessed_augm_2x/tgt-val.csv

# Training
save_model: models/mayr_augm_23_12_2/model
save_checkpoint_steps: 10000
keep_checkpoint: 20
seed: 42
train_steps: 200000
valid_steps: 10000
warmup_steps: 8000
report_every: 100

decoder_type: transformer
encoder_type: transformer
word_vec_size: 256
hidden_size: 256
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 4096
batch_type: tokens
normalization: tokens

dropout: [0.1]
label_smoothing: 0.0

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 1
gpu_ranks: [0]
